VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CInitWinDll"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Description = "amicy:Win32 Dynamic-Link Library init class"
'===================================================================================================
'| 模 块 名 | CInitWinDll
'| 描    述 | amicy:Dll Init class
'| 说    明 | 不要修改该类
'| 创 建 人 | amicy QQ:35723195 MSN:xb@live.it
'| 日    期 | 2008-10-10 16:55:07
'| 版    本 | 1.0.0
'===================================================================================================
